### ISSUE TITLE
Versioning issues and LinAlgError

### ISSUE THREAD

**Issue by Juansess** [PennyLaneAI/DatasetsSource#2]
When installing through pip and importing, the following error is thrown:
`AttributeError: module 'pennylane' has no attribute 'disable_return'`

After manually inforcing `pennylane==0.30.0` as show in requirements.txt, numpy is downgraded to 1.23.5. Now the error when importing is:
`AttributeError: module 'numpy' has no attribute 'dtypes'`

Then, after upgrading numpy again to 2.3.1, the library can be finally imported.

However, when running `qd.qchem_data_generate("/content/DatasetsSource/quantum_datasets/xyzfiles/q.1-1/schm-1/h2.xyz")`, this error is raised:
`LinAlgError: Eigenvalues did not converge`
